[2024-06-23T08:19:28.505+0000] {processor.py:161} INFO - Started process (PID=515) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:28.506+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:19:28.507+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:19:28.507+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:28.512+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:19:28.510+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-06-23T08:19:28.513+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:28.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.021 seconds
[2024-06-23T08:19:44.681+0000] {processor.py:161} INFO - Started process (PID=520) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:44.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:19:44.684+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:19:44.684+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:44.696+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:19:44.691+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-06-23T08:19:44.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:44.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.040 seconds
[2024-06-23T08:19:45.711+0000] {processor.py:161} INFO - Started process (PID=525) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:45.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:19:45.715+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:19:45.715+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:45.723+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:19:45.721+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 1, in <module>
    from datetime import datetime,timedeltae
ImportError: cannot import name 'timedeltae' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'timedelta'?
[2024-06-23T08:19:45.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:45.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.035 seconds
[2024-06-23T08:19:47.758+0000] {processor.py:161} INFO - Started process (PID=530) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:47.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:19:47.760+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:19:47.760+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:47.764+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:19:47.763+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:19:47.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:47.773+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.021 seconds
[2024-06-23T08:19:52.827+0000] {processor.py:161} INFO - Started process (PID=535) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:52.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:19:52.831+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:19:52.830+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:52.836+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:19:52.835+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 13
    )
     ^
SyntaxError: expected ':'
[2024-06-23T08:19:52.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:52.857+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.037 seconds
[2024-06-23T08:19:56.873+0000] {processor.py:161} INFO - Started process (PID=546) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:56.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:19:56.875+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:19:56.875+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:56.881+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:19:56.880+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 12
    dag_id = 
    ^^^^^^^^
SyntaxError: expected argument value expression
[2024-06-23T08:19:56.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:19:56.897+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.030 seconds
[2024-06-23T08:20:07.979+0000] {processor.py:161} INFO - Started process (PID=551) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:07.980+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:20:07.980+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:20:07.980+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:07.983+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:20:07.982+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 14
    )
     ^
SyntaxError: expected ':'
[2024-06-23T08:20:07.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:07.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.017 seconds
[2024-06-23T08:20:25.156+0000] {processor.py:161} INFO - Started process (PID=562) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:25.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:20:25.158+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:20:25.158+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:25.161+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:20:25.161+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 13
    default_args = 
    ^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2024-06-23T08:20:25.162+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:25.183+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.033 seconds
[2024-06-23T08:20:31.232+0000] {processor.py:161} INFO - Started process (PID=567) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:31.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:20:31.235+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:20:31.234+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:31.237+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:20:31.237+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 15
    )
     ^
SyntaxError: expected ':'
[2024-06-23T08:20:31.238+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:31.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.030 seconds
[2024-06-23T08:20:39.334+0000] {processor.py:161} INFO - Started process (PID=572) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:39.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:20:39.335+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:20:39.335+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:39.338+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:20:39.337+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 16
    )
     ^
SyntaxError: expected ':'
[2024-06-23T08:20:39.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:39.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.018 seconds
[2024-06-23T08:20:56.514+0000] {processor.py:161} INFO - Started process (PID=583) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:56.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:20:56.518+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:20:56.518+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:56.524+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:20:56.523+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 16
    )
     ^
SyntaxError: expected ':'
[2024-06-23T08:20:56.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:20:56.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.038 seconds
[2024-06-23T08:21:00.578+0000] {processor.py:161} INFO - Started process (PID=588) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:00.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:21:00.582+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:00.582+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:00.587+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:00.586+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 17
    )
     ^
SyntaxError: expected ':'
[2024-06-23T08:21:00.587+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:00.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.037 seconds
[2024-06-23T08:21:12.756+0000] {processor.py:161} INFO - Started process (PID=593) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:12.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:21:12.760+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:12.760+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:12.765+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:12.764+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 14
    start_date= datetime.now()
                
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-23T08:21:12.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:12.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.033 seconds
[2024-06-23T08:21:20.829+0000] {processor.py:161} INFO - Started process (PID=598) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:20.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:21:20.831+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:20.831+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:20.836+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:20.835+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 14
    start_date= datetime.now()
                ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-23T08:21:20.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:20.852+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.027 seconds
[2024-06-23T08:21:24.889+0000] {processor.py:161} INFO - Started process (PID=609) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:24.890+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:21:24.893+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:24.892+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:24.899+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:24.898+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 14
    start_date= datetime.now()
                ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-23T08:21:24.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:24.918+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.035 seconds
[2024-06-23T08:21:26.919+0000] {processor.py:161} INFO - Started process (PID=614) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:26.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:21:26.922+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:26.922+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:26.927+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:26.926+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 14
    start_date= datetime.now()
                ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-23T08:21:26.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:26.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.029 seconds
[2024-06-23T08:21:27.951+0000] {processor.py:161} INFO - Started process (PID=619) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:27.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:21:27.953+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:27.953+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:27.956+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:27.955+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 14
    start_date= datetime.now()
                ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-23T08:21:27.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:27.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.020 seconds
[2024-06-23T08:21:29.987+0000] {processor.py:161} INFO - Started process (PID=624) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:29.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:21:29.989+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:29.989+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:29.993+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:29.992+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 14
    start_date= datetime.now()
                ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-23T08:21:29.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:30.011+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.028 seconds
[2024-06-23T08:21:38.095+0000] {processor.py:161} INFO - Started process (PID=629) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:38.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:21:38.098+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:38.098+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:38.104+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:38.103+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 14
    start_date= datetime.now()
                ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-06-23T08:21:38.105+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:38.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.037 seconds
[2024-06-23T08:21:49.220+0000] {processor.py:161} INFO - Started process (PID=634) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:49.223+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:21:49.225+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:49.224+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:49.230+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:49.229+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 16
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 11
[2024-06-23T08:21:49.230+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:49.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.036 seconds
[2024-06-23T08:21:59.342+0000] {processor.py:161} INFO - Started process (PID=644) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:59.345+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:21:59.347+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:59.346+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:59.353+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:21:59.352+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:21:59.354+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:21:59.369+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.034 seconds
[2024-06-23T08:22:02.383+0000] {processor.py:161} INFO - Started process (PID=649) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:02.384+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:22:02.386+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:02.385+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:02.394+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:02.393+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:22:02.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:02.413+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.035 seconds
[2024-06-23T08:22:05.448+0000] {processor.py:161} INFO - Started process (PID=654) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:05.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:22:05.453+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:05.452+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:05.459+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:05.458+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:22:05.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:05.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.036 seconds
[2024-06-23T08:22:09.501+0000] {processor.py:161} INFO - Started process (PID=659) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:09.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:22:09.505+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:09.504+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:09.510+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:09.509+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 18
    task_id = 
    ^^^^^^^^^
SyntaxError: expected argument value expression
[2024-06-23T08:22:09.511+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:09.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.033 seconds
[2024-06-23T08:22:16.606+0000] {processor.py:161} INFO - Started process (PID=664) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:16.608+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:22:16.610+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:16.609+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:16.617+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:16.616+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:22:16.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:16.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.034 seconds
[2024-06-23T08:22:26.772+0000] {processor.py:161} INFO - Started process (PID=675) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:26.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:22:26.776+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:26.776+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:26.790+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:26.789+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 19
    postgres_conn_id = 
    ^^^^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2024-06-23T08:22:26.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:26.803+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.073 seconds
[2024-06-23T08:22:32.798+0000] {processor.py:161} INFO - Started process (PID=680) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:32.799+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:22:32.801+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:32.801+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:32.809+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:32.807+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:22:32.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:32.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.042 seconds
[2024-06-23T08:22:34.821+0000] {processor.py:161} INFO - Started process (PID=685) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:34.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:22:34.824+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:34.824+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:34.831+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:34.830+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:22:34.832+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:34.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.034 seconds
[2024-06-23T08:22:35.885+0000] {processor.py:161} INFO - Started process (PID=690) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:35.886+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:22:35.888+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:35.887+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:35.891+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:22:35.890+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:22:35.891+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:22:35.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.018 seconds
[2024-06-23T08:23:06.200+0000] {processor.py:161} INFO - Started process (PID=701) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:23:06.201+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:23:06.204+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:23:06.204+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:23:06.207+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:23:06.206+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:23:06.208+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:23:06.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.033 seconds
[2024-06-23T08:23:36.507+0000] {processor.py:161} INFO - Started process (PID=712) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:23:36.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:23:36.511+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:23:36.511+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:23:36.518+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:23:36.516+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:23:36.518+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:23:36.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.038 seconds
[2024-06-23T08:24:06.803+0000] {processor.py:161} INFO - Started process (PID=723) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:24:06.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:24:06.806+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:24:06.806+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:24:06.811+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:24:06.809+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:24:06.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:24:06.829+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.033 seconds
[2024-06-23T08:24:37.158+0000] {processor.py:161} INFO - Started process (PID=734) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:24:37.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:24:37.161+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:24:37.160+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:24:37.166+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:24:37.165+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:24:37.167+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:24:37.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.032 seconds
[2024-06-23T08:25:07.456+0000] {processor.py:161} INFO - Started process (PID=745) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:25:07.457+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:25:07.460+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:25:07.459+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:25:07.465+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:25:07.463+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:25:07.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:25:07.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.037 seconds
[2024-06-23T08:25:37.769+0000] {processor.py:161} INFO - Started process (PID=756) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:25:37.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:25:37.772+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:25:37.772+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:25:37.778+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:25:37.776+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:25:37.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:25:37.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.036 seconds
[2024-06-23T08:26:08.093+0000] {processor.py:161} INFO - Started process (PID=767) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:26:08.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:26:08.096+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:26:08.096+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:26:08.101+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:26:08.099+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:26:08.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:26:08.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.034 seconds
[2024-06-23T08:26:38.418+0000] {processor.py:161} INFO - Started process (PID=778) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:26:38.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:26:38.421+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:26:38.421+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:26:38.428+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:26:38.425+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:26:38.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:26:38.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.040 seconds
[2024-06-23T08:27:08.751+0000] {processor.py:161} INFO - Started process (PID=789) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:27:08.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:27:08.755+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:27:08.755+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:27:08.761+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:27:08.759+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 8, in <module>
    'retry_delay': timedelta(mimutes = 5)
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mimutes' is an invalid keyword argument for __new__()
[2024-06-23T08:27:08.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:27:08.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.037 seconds
[2024-06-23T08:27:12.796+0000] {processor.py:161} INFO - Started process (PID=794) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:27:12.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:27:12.799+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:27:12.799+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:27:12.816+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:27:12.813+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 17, in <module>
    task1 = PostgresOperator(
            ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-06-23T08:27:12.817+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:27:12.829+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.042 seconds
[2024-06-23T08:27:19.900+0000] {processor.py:161} INFO - Started process (PID=799) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:27:19.902+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:27:19.904+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:27:19.903+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:27:19.916+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:27:19.914+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 17, in <module>
    task1 = PostgresOperator(
            ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-06-23T08:27:19.917+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:27:19.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.042 seconds
[2024-06-23T08:27:50.196+0000] {processor.py:161} INFO - Started process (PID=810) to work on /opt/airflow/dags/aws_etl.py
[2024-06-23T08:27:50.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/aws_etl.py for tasks to queue
[2024-06-23T08:27:50.199+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:27:50.199+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:27:50.210+0000] {logging_mixin.py:188} INFO - [2024-06-23T08:27:50.208+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/aws_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/aws_etl.py", line 17, in <module>
    task1 = PostgresOperator(
            ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-06-23T08:27:50.211+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/aws_etl.py
[2024-06-23T08:27:50.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/aws_etl.py took 0.039 seconds
