[2024-09-24T04:41:56.870+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-24T04:41:56.890+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.load_csv_to_postgres manual__2024-09-24T04:41:55.307458+00:00 [queued]>
[2024-09-24T04:41:56.894+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.load_csv_to_postgres manual__2024-09-24T04:41:55.307458+00:00 [queued]>
[2024-09-24T04:41:56.895+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-09-24T04:41:56.901+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_csv_to_postgres> on 2024-09-24 04:41:55.307458+00:00
[2024-09-24T04:41:56.906+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'load_csv_to_postgres', 'manual__2024-09-24T04:41:55.307458+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmpvyed_quj']
[2024-09-24T04:41:56.907+0000] {standard_task_runner.py:91} INFO - Job 120: Subtask load_csv_to_postgres
[2024-09-24T04:41:56.907+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=238) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-24T04:41:56.908+0000] {standard_task_runner.py:63} INFO - Started process 240 to run task
[2024-09-24T04:41:56.935+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.load_csv_to_postgres manual__2024-09-24T04:41:55.307458+00:00 [running]> on host b6455cb83403
[2024-09-24T04:41:57.085+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jack' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T04:41:55.307458+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-24T04:41:55.307458+00:00'
[2024-09-24T04:41:57.086+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-24T04:41:57.093+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-24T04:41:57.093+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/postgres_dag.py", line 12, in load_csv_topostgress
    df = pd.read_csv(csv_file_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/data/retail_clean.csv'
[2024-09-24T04:41:57.101+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=load_csv_to_postgres, run_id=manual__2024-09-24T04:41:55.307458+00:00, execution_date=20240924T044155, start_date=20240924T044156, end_date=20240924T044157
[2024-09-24T04:41:57.106+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 120 for task load_csv_to_postgres ([Errno 2] No such file or directory: '/opt/data/retail_clean.csv'; 240)
[2024-09-24T04:41:57.145+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-24T04:41:57.156+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-24T04:41:57.157+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
