[2024-06-25T10:06:33.749+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T10:06:33.766+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2024-06-25T10:06:32.569381+00:00 [queued]>
[2024-06-25T10:06:33.769+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2024-06-25T10:06:32.569381+00:00 [queued]>
[2024-06-25T10:06:33.769+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-25T10:06:33.774+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-06-25 10:06:32.569381+00:00
[2024-06-25T10:06:33.777+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'manual__2024-06-25T10:06:32.569381+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmp6n38c6y_']
[2024-06-25T10:06:33.778+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=17369) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-25T10:06:33.778+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask create_postgres_table
[2024-06-25T10:06:33.778+0000] {standard_task_runner.py:63} INFO - Started process 17370 to run task
[2024-06-25T10:06:33.805+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2024-06-25T10:06:32.569381+00:00 [running]> on host 3b316f897547
[2024-06-25T10:06:33.848+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jack' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T10:06:32.569381+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T10:06:32.569381+00:00'
[2024-06-25T10:06:33.849+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T10:06:33.856+0000] {sql.py:276} INFO - Executing: 
            CREATE SCHEMA IF NOT EXISTS customer_schema;

            DROP TABLE IF EXISTS customer_schema.customer_table;

            CREATE TABLE customer_schema.customer_table (
                InvoiceNo TEXT,
                StockCode TEXT,
                "Description" TEXT,
                Quantity INT,
                InvoiceDate TIMESTAMP,
                UnitPrice FLOAT,
                CustomerID TEXT,
                Country TEXT
            );
             
[2024-06-25T10:06:33.860+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T10:06:33.864+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2024-06-25T10:06:33.866+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, run_id=manual__2024-06-25T10:06:32.569381+00:00, execution_date=20240625T100632, start_date=20240625T100633, end_date=20240625T100633
[2024-06-25T10:06:33.870+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task create_postgres_table (The conn_id `postgres_localhost` isn't defined; 17370)
[2024-06-25T10:06:33.880+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-25T10:06:33.887+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T10:06:33.887+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
