[2024-06-25T10:11:17.597+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T10:11:17.612+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2024-06-25T10:11:17.239772+00:00 [queued]>
[2024-06-25T10:11:17.615+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2024-06-25T10:11:17.239772+00:00 [queued]>
[2024-06-25T10:11:17.615+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-25T10:11:17.620+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-06-25 10:11:17.239772+00:00
[2024-06-25T10:11:17.624+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'manual__2024-06-25T10:11:17.239772+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmpdcasqgi8']
[2024-06-25T10:11:17.625+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask create_postgres_table
[2024-06-25T10:11:17.625+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=17548) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-25T10:11:17.625+0000] {standard_task_runner.py:63} INFO - Started process 17549 to run task
[2024-06-25T10:11:17.645+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2024-06-25T10:11:17.239772+00:00 [running]> on host 3b316f897547
[2024-06-25T10:11:17.682+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jack' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T10:11:17.239772+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T10:11:17.239772+00:00'
[2024-06-25T10:11:17.682+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T10:11:17.688+0000] {sql.py:276} INFO - Executing: 
            CREATE SCHEMA IF NOT EXISTS customer_schema;

            DROP TABLE IF EXISTS customer_schema.customer_table;

            CREATE TABLE customer_schema.customer_table (
                InvoiceNo TEXT,
                StockCode TEXT,
                "Description" TEXT,
                Quantity INT,
                InvoiceDate TIMESTAMP,
                UnitPrice FLOAT,
                CustomerID TEXT,
                Country TEXT
            );
             
[2024-06-25T10:11:17.693+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-25T10:11:17.697+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-25T10:11:25.705+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T10:11:25.708+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Temporary failure in name resolution

[2024-06-25T10:11:25.728+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, run_id=manual__2024-06-25T10:11:17.239772+00:00, execution_date=20240625T101117, start_date=20240625T101117, end_date=20240625T101125
[2024-06-25T10:11:25.740+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task create_postgres_table (could not translate host name "host.docker.local" to address: Temporary failure in name resolution
; 17549)
[2024-06-25T10:11:25.778+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-25T10:11:25.796+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T10:11:25.797+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
